import{a as d,S as m,i as f}from"./assets/vendor-DggqAQP3.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="49186769-dabefba962826c776b77806d1",h="https://pixabay.com/api/";function y(o){return d.get(h,{params:{key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data.hits).catch(t=>(console.error("Error fetching images:",t.message),[]))}const g=new m(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function b(o){return o.map(({webformatURL:t,largeImageURL:s,tags:i,likes:e,views:r,comments:a,downloads:u})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${t}" alt="${i}" loading="lazy" />
        </a>
        <div class="thumb-block">
          <div class="block"><h2 class="tittle">Likes</h2><p class="amount">${e}</p></div>
          <div class="block"><h2 class="tittle">Views</h2><p class="amount">${r}</p></div>
          <div class="block"><h2 class="tittle">Comments</h2><p class="amount">${a}</p></div>
          <div class="block"><h2 class="tittle">Downloads</h2><p class="amount">${u}</p></div>
        </div>
      </li>`).join("")}function v(o){const t=document.querySelector(".gallery");t.innerHTML=b(o),g.refresh()}function n(o){f.error({title:"Error",message:o,position:"topRight"})}function L(){document.querySelector(".loader").style.display="block"}function c(){document.querySelector(".loader").style.display="none"}const l=document.querySelector(".form-search"),q=document.querySelector(".input-search"),S=document.querySelector(".gallery");l.addEventListener("submit",function(o){o.preventDefault();const t=q.value.trim();if(t===""){n("Please enter a search query!");return}S.innerHTML="",L(),y(t).then(s=>{if(c(),s.length===0){n("Sorry, there are no images matching your search query. Please try again!");return}v(s)}).catch(s=>{c(),n("Error fetching images. Please try again!"),console.error("Помилка сервера:",s.message)}),l.reset()});
//# sourceMappingURL=index.js.map
